name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Temporarily disabled - using Vercel auto-deploy instead

jobs:
  # Disabled - using Vercel auto-deploy
  placeholder:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder job
      run: echo "CI/CD temporarily disabled - using Vercel auto-deploy"
